services:
    meshplay:
        image: khulnasoft/meshplay:playground-latest
        environment:
            - PROVIDER_BASE_URLS=https://meshplay.khulnasoft.com
            - ADAPTER_URLS=meshplay-istio:10000 meshplay-linkerd:10001 meshplay-consul:10002 meshplay-nsm:10004 meshplay-app-mesh:10005 meshplay-kuma:10007 meshplay-traefik-mesh:10006 meshplay-nginx-sm:10010 meshplay-cilium:10012
            - EVENT=meshplayLocal
            - PORT=9081
            - MESHPLAY_SERVER_CALLBACK_URL=https://playground.meshplay.khulnasoft.com/api/user/token
            - PROVIDER=Meshplay
        volumes:
            - $HOME/.kube:/home/appuser/.kube:ro
            - $HOME/.minikube:$HOME/.minikube:ro
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 9081:9081
        restart: always
    # nginx:
    #     image: nginx:latest
    #     labels:
    #         - "com.centurylinklabs.watchtower.enable=true"
    #     ports:
    #         - 443:443
    #         - 80:80
    #     volumes:
    #         - /etc/letsencrypt/:/etc/letsencrypt/
    #         - /root/meshplay/install/playground/docker/nginx.conf:/etc/nginx/nginx.conf
    #     restart: always
    meshplay-istio:
        image: khulnasoft/meshplay-istio:stable-latest
        ports:
            - 10000:10000
        restart: always
    meshplay-linkerd:
       image: khulnasoft/meshplay-linkerd:stable-latest
       ports:
            - 10001:10001
       restart: always
    meshplay-consul:
       image: khulnasoft/meshplay-consul:stable-latest
       ports:
            - 10002:10002
       restart: always
    meshplay-kuma:
       image: khulnasoft/meshplay-kuma:stable-latest
       ports:
            - 10007:10007
       restart: always
    meshplay-nginx-sm:
       image: khulnasoft/meshplay-nginx-sm:stable-latest
       ports:
            - 10010:10010
       restart: always
    meshplay-cilium:
        image: khulnasoft/meshplay-cilium:stable-latest
        ports:
            - 10012:10012
        restart: always

version: "3"