contexts:
    gke:
        channel: stable
        components:
            - meshplay-istio
        endpoint: http://localhost:9081
        platform: gke
        token: default
        version: latest
    local:
        endpoint: http://localhost:9081
        token: default
        platform: docker
        components:
            - meshplay-istio
        channel: stable
        version: latest
current-context: local
tokens:
    - location: auth.json
      name: default
