apiVersion: v1
kind: Service
metadata:
  name: {{ include "meshplay.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "meshplay.labels" . | nindent 4 }}
  annotations:
{{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.target_port }}
      protocol: TCP
      name: http
  selector:
    {{- include "meshplay.selectorLabels" . | nindent 4 }}
