{{- if .Values.meshplaygateway.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: meshplay
spec:
  hosts:
  - "*"
  gateways:
  - meshplay-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: meshplay
        port:
          number: 9081
{{- end }}