# Test configuration file for running performance benchmarks
# See: https://docs.meshplay.io/guides/performance-management#running-performance-benchmarks-through-meshplayctl
test:
  smp_version: v0.0.1
  
  # The name of the test
  name: Performance Profile for Meshplay's Nightly Integration Testing
  labels: {}
  
  # Test configuration to be defined here
  clients:
    - internal: false
      load_generator: fortio
      protocol: 1
      connections: 2
      rps: 10
      headers: {}
      cookies: {}
      body: ''
      content_type: ''
      endpoint_urls:
        - 'https://meshplay.io'
  duration: 2s

# Service mesh under test in Service Mesh Performance Spec format
# See: https://github.com/service-mesh-performance/service-mesh-performance/blob/master/protos/service_mesh.proto
mesh:
  type: 3
