run:
  timeout: 5m

  skip-files:
    # https://github.com/meshplay/meshplay/issues/7761
    - server/handlers/doc.go
    # @Aisuko We need to fix the CI ASAP
    - server/models/meshmodel/core/register.go
