{{- if and (not .Values.serviceAccountNameOverride) .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "meshplay-istio.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "meshplay-istio.labels" . | nindent 4 }}
{{- end -}}
