apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: my-ip-space
  name: meshplay
  labels:
    app: meshplay
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: meshplay
status:
  loadBalancer: {}
