apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yaml
    kompose.version: 1.32.0 ()
  # creationTimestamp: null
  labels:
    io.kompose.service: meshplay-consul
  name: meshplay-consul
spec:
  ports:
  - name: "10002"
    port: 10002
    targetPort: 10002
  selector:
    io.kompose.service: meshplay-consul
status:
  loadBalancer: {}
