apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yaml
    kompose.version: 1.32.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: meshplay-nsm
  name: meshplay-nsm
spec:
  selector:
    matchLabels:
      io.kompose.service: meshplay-nsm
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: meshplay-nsm
    spec:
      serviceAccount: meshplay-server
      containers:
        - image: khulnasoft/meshplay-nsm:stable-latest
          imagePullPolicy: Always
          name: meshplay-nsm
          ports:
            - containerPort: 10004
          resources: {}
      restartPolicy: Always
status: {}
