apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yaml
    kompose.version: 1.32.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: meshplay
  name: meshplay
spec:
  selector:
    matchLabels:
      io.kompose.service: meshplay
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: meshplay
    spec:
      serviceAccountName: meshplay-server
      containers:
      - env:
        - name: EVENT
          value: meshplayLocal
        - name: PROVIDER_BASE_URLS
          value: https://meshplay.khulnasoft.com
        - name: ADAPTER_URLS
          value: meshplay-istio:10000 meshplay-linkerd:10001 meshplay-consul:10002 meshplay-nsm:10004 meshplay-app-mesh:10005 meshplay-kuma:10007 meshplay-nginx-sm:10010
        image: khulnasoft/meshplay:stable-latest
        imagePullPolicy: Always
        name: meshplay
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
