apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yaml
    kompose.version: 1.32.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: meshplay-app-mesh
  name: meshplay-app-mesh
spec:
  ports:
  - name: "10005"
    port: 10005
    targetPort: 10005
  selector:
    io.kompose.service: meshplay-app-mesh
status:
  loadBalancer: {}
