name: Staging Playground CNCF - Deploy
on:
  workflow_call:
  workflow_dispatch:
jobs:
    cncf-staging-playground-rollout:
        name: Update Meshplay on CNCF staging playground
        if: github.repository == 'meshplay/meshplay'
        runs-on: ubuntu-latest 
        steps:
        - name: Upgrade Meshplay Helm Release
          uses: appleboy/ssh-action@v1.0.3
          with:
              host: ${{ secrets.METAL_SERVER3 }}
              username: root
              key: ${{ secrets.METAL_SSH_KEY }}
              script: |
                meshplayctl system channel set edge
                PROVIDER_BASE_URLS="https://staging-meshplay.khulnasoft.com" meshplayctl system update
