name: email test
on:
    workflow_dispatch:
      inputs:
        release-tag:
          type: string
          required: true
          default: v0.6.103
        to: 
          type: string
          required: true

    
jobs:
  email-meshplay-release-notes-workflow:
    name: Email Meshplay Release Notes
    uses: layer5labs/meshplay-extensions-packages/.github/workflows/notify-email.yml@master
    secrets: 
      token: ${{ secrets.GH_ACCESS_TOKEN }}
      MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
    with:
      release-tag: ${{inputs.release-tag}}
      to: ${{inputs.to}}
