name: Meshplayctl
on:
  push:
    branches:
      - "master"
    paths:
      - "meshplayctl/**"
  pull_request:
    branches:
      - "master"
    paths:
      - "meshplayctl/**"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"

jobs:
  golangci:
    name: golangci-lint
    if: github.repository == 'meshplay/meshplay'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59
          working-directory: meshplayctl
          args: --timeout 10m --verbose
          skip-cache: true
  meshplayctl_build:
    name: Meshplayctl build & release
    if: github.repository == 'meshplay/meshplay'
    runs-on: macos-latest
    needs: [golangci]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - name: Setup Cache
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: goreleaser WITHOUT tag
        uses: goreleaser/goreleaser-action@v5
        if: success() && startsWith(github.ref, 'refs/tags/') == false
        env:
          RELEASE_CHANNEL: "edge"
        with:
          version: latest
          args: release --snapshot --skip-publish --clean
  meshplayctl_docs:
    if: "always() && github.event_name != 'pull_request' && github.repository == 'meshplay/meshplay' "
    runs-on: ubuntu-22.04
    steps:
      - name: Skip if needed
        run: |
          echo "this is it ${{ needs.SkipIfNeeded.outputs.skipdocupdate }} "
          if [ "${{github.event_name }}" == "push" ];then
            echo "version=edge" >> $GITHUB_ENV
          fi
          if [ "${{github.event_name }}" == "release" ];then
            echo "version=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
          fi
      - uses: actions/checkout@v4
        with:
          repository: meshplay/meshplay
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          check-latest: "true"
      - name: Run script 📜
        run: |
          cd meshplayctl
          make docs

      - name: Pull changes from remote
        run: git pull origin master

      - name: Commit ✅
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: docs
          commit_user_name: l5io
          commit_user_email: ci@khulnasoft.com
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit_options: "--signoff"
          commit_message: "[Docs] Update meshplayctl docs"