name: Update Script in VM
on:
    push:
      branches:
        - 'master'
      paths:
        - '$GITHUB_WORKSPACE/install/playground/playground-cleanup.sh'
jobs:
    update_script:
        runs-on: ubuntu-latest
    
        steps:
        - name: Update Script in VM
          uses: appleboy/ssh-action@master
          with:
            host: 147.75.47.9
            username: root
            key: ${{ secrets.METAL_SSH_KEY }}
            script: |
                cd meshplay/install/playground; curl -O https://raw.githubusercontent.com/meshplay/meshplay/meshplay/install/playground-cleanup.sh
          